variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
  DOCKER_TAG: "latest"

.node-job:
  before_script:
  - cd frontend 
  - npm ci --cache .npm --prefer-offline
  cache:
    key: npm
    paths:
     - .npm/
     
stages: 
  - lint 
  - build  
  - test   
  - deploy

Lint-frontend:
  stage: lint
  extends: .node-job
  script:             
    - npm run lint 


Build-frontend:
  stage: build
  extends: .node-job
  script:           
    - npm run build     
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/       

Test-frontend:
  stage: test
  extends: .node-job
  script:    
    - export CHROME_BIN=/usr/bin/chromium-browser                 
    - npm run test:coverage  
  

Deploy-frontend:
  stage: deploy  
  script:
    - cd frontend 
    - sudo rsync -avu dist/bio-ton-field-management-system/ /var/www/front
    - sudo chown www-data:www-data /var/www/front/* 
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual


Build-backend:
  variables:
    GIT_DEPTH: 100
  stage: build
  script:    
    - docker system prune -af
    - docker build -t fms-back:$DOCKER_TAG .   


Deploy-backend:
  stage: deploy
  script:
    - docker rm -f fms-back || true
    - docker run --name fms-back -p 8080:80 -v /var/log/fms:/app/logs --restart always  -d fms-back:$DOCKER_TAG  
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual