variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
     
stages: 
  - lint         
  - build
  - test
  - deploy

Lint-front:
  stage: lint
  script:
    - cd frontend
    - npm ci
    - npm run lint

#Build-front:
#  stage: build
#  script:
#    - cd frontend
#    - npm update    
#    - npm run build 
#   - sudo rsync -zvh dist/bio-ton-field-management-system/ /var/www/front
#    - sudo chown www-data:www-data /var/www/front/*

Build-backend:
  stage: build
  script:    
    - docker system prune -af
    - docker build -t fms-back:dev-ops .

Test-front:
  stage: test
  script:
    - cd frontend
    - npm ci
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm run test:coverage

Deploy-backend:
  stage: deploy
  script:
    - docker rm -f fms-back || true
    - docker run --name fms-back -p 8080:80 -d fms-back:dev-ops  

Deploy-front:
  stage: deploy
  script:
    - cd frontend
    - npm ci
    - npm update    
    - npm run deploy 
    - sudo rsync -zvh dist/bio-ton-field-management-system/ /var/www/front
    - sudo chown www-data:www-data /var/www/front/*  
    