variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
     
stages: 
  - lint         
  - build
  - test
  - deploy


Build-backend:
  stage: build
  script:    
    - docker system prune -af
    - docker build -t fms-back:dev-ops .


Deploy-backend:
  stage: deploy
  script:
    - docker rm -f fms-back || true
    - docker run --name fms-back -p 8080:80 -d fms-back:dev-ops  

Deploy-frontend:
  stage: deploy
  script:
    - cd frontend
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm ci
    - npm update    
    - npm run deploy 
    - sudo rsync -zvh dist/bio-ton-field-management-system/ /var/www/front
    - sudo chown www-data:www-data /var/www/front/*  
    