variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
  DOCKER_TAG: "latest"
     
stages: 
  - lint 
  - test        
  - build
  - deploy


Test-frontend:
  stage: lint
  script:
    - cd frontend 
    - export CHROME_BIN=/usr/bin/chromium-browser   
    - npm ci
    - npm update    
    - npm run lint 

Test-frontend:
  stage: test
  script:
    - cd frontend 
    - export CHROME_BIN=/usr/bin/chromium-browser   
    - npm ci
    - npm update    
    - npm run test 

Deploy-frontend:
  stage: deploy
  script:
    - cd frontend  
    - npm ci
    - npm update    
    - npm run build 
    - sudo rsync -zvh dist/bio-ton-field-management-system/ /var/www/front
    - sudo chown www-data:www-data /var/www/front/*  

Build-backend:
  stage: build
  script:    
    - docker system prune -af
    - docker build -t fms-back:$DOCKER_TAG .


Deploy-backend:
  stage: deploy
  script:
    - docker rm -f fms-back || true
    - docker run --name fms-back -p 8080:80  --restart always -d fms-back:$DOCKER_TAG  


    
