stages:          
  - build
  - test
  - deploy
  
Build-backend:
  stage: build
  script:
    - docker build -t fms-back:dev-ops2 .

Deploy-backend:
  stage: deploy
  script:
    - docker run -p 80:80 -d fms-back:dev-ops