stages: 
  - lint         
  - build
  - test
  - deploy

Lint-front:
  stage: lint
  script:
    - cd frontend
    - npm ci
    - npm run lint

Build-front:
  stage: lint
  script:
    - cd frontend    
    - npm run build

Build-backend:
  stage: build
  script:
    - docker system prune -a
    - docker build -t fms-back:dev-ops .

Deploy-backend:
  stage: deploy
  script:
    - docker run -p 80:80 -d fms-back:dev-ops