variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
     
stages: 
  - lint         
  - build
  - test
  - deploy

Lint-front:
  stage: lint
  script:
    - cd frontend
    - npm ci
    - npm run lint

Build-front:
  stage: build
  script:
    - cd frontend
    - npm update    
    - npm run build

Build-backend:
  stage: build
  script:    
    - docker system prune -af
    - docker build -t fms-back:dev-ops .

Test-front:
  stage: test
  script:
    - cd frontend
    - npm ci
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm run test:coverage

Deploy-backend:
  stage: deploy
  script:
    - docker stop fms-back || true
    - docker run --name fms-back -p 8080:80 -d fms-back:dev-ops