variables:
  GIT_FETCH_EXTRA_FLAGS: --tags
  DOCKER_TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  TrueVar: "true"

.node-job:
  before_script:
  - cd frontend 
  - npm ci --cache .npm --prefer-offline
  cache:
    key: npm
    paths:
     - .npm/

        
stages: 
  - lint 
  - build  
  - test   
  - deploy  

Lint-frontend:
  stage: lint
  extends: .node-job
  script:             
    - npm run lint 
  rules:
    - if: $CI_COMMIT_BRANCH == "MAIN"
      when: always
    - changes:
      - frontend/**/*
    - if: $TrueVar == "true"
      when: manual
      allow_failure: true       

Build-frontend:
  stage: build
  needs: 
    - Lint-frontend
  extends: .node-job  
  script:           
    - npm run build     
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/
  rules:
    - if: $CI_COMMIT_BRANCH == "MAIN"
      when: always
    - changes:
      - frontend/**/*
    - if: $TrueVar == "true"
      when: manual
      allow_failure: true
           

Test-frontend:
  stage: test
  needs: 
    - Build-frontend
  extends: .node-job  
  script:    
    - export CHROME_BIN=/usr/bin/chromium-browser                 
    - npm run test:coverage 
  rules:
    - if: $CI_COMMIT_BRANCH == "MAIN"
      when: always
    - changes:
      - frontend/**/*
    - if: $TrueVar == "true"
      when: manual
      allow_failure: true

Deploy-frontend-test.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-frontend
  extends: .node-job
  script:
    - npm run build:test    
    - sudo rsync -avu dist/bio-ton-field-management-system/ /var/www/test.lan.bioton-fms-ru
    - sudo chown www-data:www-data /var/www/test.lan.bioton-fms-ru/*
  rules:
    - if: $CI_COMMIT_BRANCH == "MAIN"
      when: always         

    - if: $TrueVar == "true"
      when: manual
      allow_failure: true
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/

Deploy-frontend-test2.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-frontend
  extends: .node-job
  script:    
    - npm run build:test2    
    - sudo rsync -avu dist/bio-ton-field-management-system/ /var/www/test2.lan.bioton-fms-ru
    - sudo chown www-data:www-data /var/www/test2.lan.bioton-fms-ru/*    
  rules:    
    - when: manual        
  allow_failure: true
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/ 

Deploy-frontend-test3.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-frontend
  extends: .node-job
  script:      
    - npm run build:test3        
    - sudo rsync -avu dist/bio-ton-field-management-system/ /var/www/test3.lan.bioton-fms-ru
    - sudo chown www-data:www-data /var/www/test3.lan.bioton-fms-ru/*     
  rules:    
    - when: manual        
  allow_failure: true
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/

Deploy-frontend-stage.bioton-fms.ru:
  stage: deploy
  needs: 
    - Test-frontend
  extends: .node-job
  script:        
    - npm run build:stage
    - rsync -avu dist/bio-ton-field-management-system/ user@stage.bioton-fms.ru:/var/www/stage   
  rules:    
    - when: manual        
  allow_failure: true
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist/  

Build-backend:
  stage: build
  script:
    - echo $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA        
    - mkdir dir
    - cd dir
    - git clone git@git.bioton-fms.ru:BioTon/fms.git .
    - git checkout ${CI_COMMIT_BRANCH}
    - docker build -t fms-back:$DOCKER_TAG .   
    - docker image tag fms-back:$DOCKER_TAG git.bioton-fms.ru:5050/bioton/fms/backend:$DOCKER_TAG
    - cat ~/registry.txt | docker login --username cicd --password-stdin git.bioton-fms.ru:5050
    - docker image push git.bioton-fms.ru:5050/bioton/fms/backend:$DOCKER_TAG
  rules:
    - changes:
      - "frontend/**/*"
      when: manual
      allow_failure: true
    - when: always


Test-backend:  
  stage: test
  needs: 
    - Build-backend  
  script:
    - mkdir dir
    - cd dir
    - git clone git@git.bioton-fms.ru:BioTon/fms.git .
    - git checkout ${CI_COMMIT_BRANCH}
    - dotnet build -c release .tools/BioTonFMS.Version
    - cd .UnitTests/BiotonFMS.Telematica.Tests
    - dotnet test --logger:trx 
  rules:
    - changes:
      - "frontend/**/*"
      when: manual
      allow_failure: true
    - when: always

Deploy-backend-test.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-backend
    - Build-TrackerTcpServer
    - Build-TrackerMessage   
  script:
    - docker rm -f fms-backend || true
    - docker run --name fms-backend -p 8080:80 -v /var/log/fms/test:/app/logs -v /etc/fms/test:/app/config --restart always  -d fms-back:$DOCKER_TAG
    - docker rm -f fms-tracker-tcp-server-test || true
    - docker run --name fms-tracker-tcp-server-test -p 8090:6000 -v /var/log/fms/tracker-tcp-server/test:/app/logs -v /etc/fms/tracker-tcp-server/test:/app/config --restart always  -d fms-tracker-tcp-server:$DOCKER_TAG
    - docker rm -f fms-tracker-message-test || true
    - docker run --name fms-tracker-message-test -p 8190:6000 -v /var/log/fms/tracker-message/test:/app/logs -v /etc/fms/tracker-message/test:/app/config --restart always  -d git.bioton-fms.ru:5050/bioton/fms/tracker-message:$DOCKER_TAG
  rules:    
    - changes:
      - frontend/**/*        
      when: manual          
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: manual
  
Deploy-backend-test2.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-backend
    - Build-TrackerTcpServer
    - Build-TrackerMessage 
  script:
    - docker rm -f fms-backend-test2 || true
    - docker run --name fms-backend-test2 -p 8081:80 -v /var/log/fms/test2:/app/logs -v /etc/fms/test2:/app/config --restart always  -d fms-back:$DOCKER_TAG      
    - docker rm -f fms-tracker-tcp-server-test2 || true
    - docker run --name fms-tracker-tcp-server-test2 -p 8091:6000 -v /var/log/fms/tracker-tcp-server/test2:/app/logs -v /etc/fms/tracker-tcp-server/test2:/app/config --restart always -d git.bioton-fms.ru:5050/bioton/fms/tracker-tcp-server:$DOCKER_TAG
    - docker rm -f fms-tracker-message-test2 || true
    - docker run --name fms-tracker-message-test2 -p 8191:6000 -v /var/log/fms/tracker-message/test2:/app/logs -v /etc/fms/tracker-message/test2:/app/config --restart always -d fms-tracker-message:$DOCKER_TAG
  rules:    
    - changes:
        - frontend/**/*        
      when: manual 
    - when: manual   
  allow_failure: true 

Deploy-backend-test3.lan.bioton-fms-ru:
  stage: deploy
  needs: 
    - Test-backend
    - Build-TrackerTcpServer
    - Build-TrackerMessage 
  script:
    - docker rm -f fms-backend-test3 || true
    - docker run --name fms-backend-test3 -p 8082:80 -v /var/log/fms/test3:/app/logs -v /etc/fms/test3:/app/config --restart always  -d fms-back:$DOCKER_TAG   
    - docker rm -f fms-tracker-tcp-server-test3 || true
    - docker run --name fms-tracker-tcp-server-test3 -p 8092:6000 -v /var/log/fms/tracker-tcp-server/test3:/app/logs -v /etc/fms/tracker-tcp-server/test3:/app/config --restart always  -d fms-tracker-tcp-server:$DOCKER_TAG
    - docker rm -f fms-tracker-message-test3 || true
    - docker run --name fms-tracker-message-test3 -p 8192:6000 -v /var/log/fms/tracker-message/test3:/app/logs -v /etc/fms/tracker-message/test3:/app/config --restart always  -d fms-tracker-message:$DOCKER_TAG
  rules:    
    - changes:
        - frontend/**/*        
      when: manual 
    - when: manual   
  allow_failure: true

Deploy-backend-stage.bioton-fms.ru:
  stage: deploy
  needs: 
    - Test-backend
    - Build-TrackerTcpServer
    - Build-TrackerMessage   
  script:
    # Backend
    - ssh user@stage.bioton-fms.ru docker rm -f fms-backend || true
    - ssh user@stage.bioton-fms.ru docker pull git.bioton-fms.ru:5050/bioton/fms/backend:$DOCKER_TAG
    - ssh user@stage.bioton-fms.ru docker run --name fms-backend -p 8080:80 -v /etc/fms/stage:/app/config -v /var/log/fms/stage:/app/logs --restart always -d git.bioton-fms.ru:5050/bioton/fms/backend:$DOCKER_TAG
    # Fms-tracker-tcp-server
    - ssh user@stage.bioton-fms.ru docker pull git.bioton-fms.ru:5050/bioton/fms/tracker-tcp-server
    - ssh user@stage.bioton-fms.ru docker rm -f fms-tracker-tcp-server || true
    - ssh user@stage.bioton-fms.ru docker run --name fms-tracker-tcp-server -p 6000:6000 -v /var/log/fms/tracker-tcp-server:/app/logs -v /etc/fms/tracker-tcp-server:/app/config --network bioton --restart always -d git.bioton-fms.ru:5050/bioton/fms/tracker-tcp-server:$DOCKER_TAG
    # Fms-tracker-message
    - ssh user@stage.bioton-fms.ru docker pull git.bioton-fms.ru:5050/bioton/fms/tracker-message
    - ssh user@stage.bioton-fms.ru docker rm -f fms-tracker-message || true
    - ssh user@stage.bioton-fms.ru docker run --name fms-tracker-message --network bioton -v /var/log/fms/tracker-message:/app/logs -v /etc/fms/tracker-message:/app/config --restart always  -d git.bioton-fms.ru:5050/bioton/fms/tracker-message:$DOCKER_TAG
  rules:    
    - changes:
        - frontend/**/*        
      when: manual 
    - when: manual   
  allow_failure: true

Build-TrackerTcpServer:
  stage: build  
  script:        
    - mkdir dir
    - cd dir
    - git clone git@git.bioton-fms.ru:BioTon/fms.git .
    - git checkout ${CI_COMMIT_BRANCH}
    - cp TrackerMessages/BioTonFMS.TrackerTcpServer/Dockerfile .
    - docker build -t fms-tracker-tcp-server:$DOCKER_TAG .   
    - docker image tag fms-tracker-tcp-server:$DOCKER_TAG git.bioton-fms.ru:5050/bioton/fms/tracker-tcp-server:$DOCKER_TAG
    - docker image push git.bioton-fms.ru:5050/bioton/fms/tracker-tcp-server:$DOCKER_TAG
  rules:
    - changes:
      - "frontend/**/*"
      when: manual
      allow_failure: true
    - when: always 

Build-TrackerMessage:
  stage: build  
  script:        
    - mkdir dir
    - cd dir
    - git clone git@git.bioton-fms.ru:BioTon/fms.git .
    - git checkout ${CI_COMMIT_BRANCH}
    - cp TrackerMessages/BioTonFMS.TrackerMessageHandler/Dockerfile .
    - rm BioTonFMSApp/appsettings.Development.json BioTonFMSApp/appsettings.json
    - docker build -t fms-tracker-message:$DOCKER_TAG .   
    - docker image tag fms-tracker-message:$DOCKER_TAG git.bioton-fms.ru:5050/bioton/fms/tracker-message:$DOCKER_TAG
    - docker image push git.bioton-fms.ru:5050/bioton/fms/tracker-message:$DOCKER_TAG
  rules:
    - changes:
      - "frontend/**/*"
      when: manual
      allow_failure: true
    - when: always 