// <auto-generated />
using System;
using BioTonFMS.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BioTonFMSApp.Migrations
{
    [DbContext(typeof(BioTonDBContext))]
    [Migration("20221229161618_TagsSeed")]
    partial class TagsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BioTonFMS.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("TrackerId")
                        .HasColumnType("integer")
                        .HasColumnName("tracker_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("TrackerId")
                        .HasDatabaseName("ix_devices_tracker_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.FuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fuel_type");

                    b.ToTable("fuel_type", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.ProtocolTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProtocolTagCode")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_tag_code");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<int>("TrackerType")
                        .HasColumnType("integer")
                        .HasColumnName("tracker_type");

                    b.HasKey("Id")
                        .HasName("pk_protocol_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_protocol_tag_tag_id");

                    b.ToTable("protocol_tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProtocolTagCode = 1,
                            Size = 1,
                            TagId = 1,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 2,
                            ProtocolTagCode = 2,
                            Size = 1,
                            TagId = 2,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 3,
                            ProtocolTagCode = 3,
                            Size = 15,
                            TagId = 3,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 4,
                            ProtocolTagCode = 4,
                            Size = 2,
                            TagId = 4,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 5,
                            ProtocolTagCode = 16,
                            Size = 2,
                            TagId = 5,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 6,
                            ProtocolTagCode = 32,
                            Size = 4,
                            TagId = 6,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 7,
                            ProtocolTagCode = 48,
                            Size = 9,
                            TagId = 7,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 8,
                            ProtocolTagCode = 51,
                            Size = 4,
                            TagId = 8,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 9,
                            ProtocolTagCode = 52,
                            Size = 2,
                            TagId = 9,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 10,
                            ProtocolTagCode = 53,
                            Size = 1,
                            TagId = 10,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 11,
                            ProtocolTagCode = 64,
                            Size = 2,
                            TagId = 11,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 12,
                            ProtocolTagCode = 65,
                            Size = 2,
                            TagId = 12,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 13,
                            ProtocolTagCode = 66,
                            Size = 2,
                            TagId = 13,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 14,
                            ProtocolTagCode = 67,
                            Size = 1,
                            TagId = 14,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 15,
                            ProtocolTagCode = 69,
                            Size = 2,
                            TagId = 15,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 16,
                            ProtocolTagCode = 70,
                            Size = 2,
                            TagId = 16,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 17,
                            ProtocolTagCode = 80,
                            Size = 2,
                            TagId = 17,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 18,
                            ProtocolTagCode = 81,
                            Size = 2,
                            TagId = 18,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 19,
                            ProtocolTagCode = 82,
                            Size = 2,
                            TagId = 19,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 20,
                            ProtocolTagCode = 83,
                            Size = 2,
                            TagId = 20,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 21,
                            ProtocolTagCode = 88,
                            Size = 2,
                            TagId = 21,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 22,
                            ProtocolTagCode = 89,
                            Size = 2,
                            TagId = 22,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 23,
                            ProtocolTagCode = 96,
                            Size = 2,
                            TagId = 23,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 24,
                            ProtocolTagCode = 97,
                            Size = 2,
                            TagId = 24,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 25,
                            ProtocolTagCode = 192,
                            Size = 4,
                            TagId = 25,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 26,
                            ProtocolTagCode = 193,
                            Size = 4,
                            TagId = 26,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 27,
                            ProtocolTagCode = 194,
                            Size = 4,
                            TagId = 27,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 28,
                            ProtocolTagCode = 196,
                            Size = 1,
                            TagId = 28,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 29,
                            ProtocolTagCode = 197,
                            Size = 1,
                            TagId = 29,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 30,
                            ProtocolTagCode = 198,
                            Size = 1,
                            TagId = 30,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 31,
                            ProtocolTagCode = 199,
                            Size = 1,
                            TagId = 31,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 32,
                            ProtocolTagCode = 200,
                            Size = 1,
                            TagId = 32,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 33,
                            ProtocolTagCode = 201,
                            Size = 1,
                            TagId = 33,
                            TrackerType = 1
                        },
                        new
                        {
                            Id = 34,
                            ProtocolTagCode = 219,
                            Size = 4,
                            TagId = 34,
                            TrackerType = 1
                        });
                });

            modelBuilder.Entity("BioTonFMS.Domain.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("imei");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SimNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("sim_number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("TrackerType")
                        .HasColumnType("integer")
                        .HasColumnName("tracker_type");

                    b.HasKey("Id")
                        .HasName("pk_trackers");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_trackers_external_id");

                    b.ToTable("trackers", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.TrackerTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("StructType")
                        .HasColumnType("integer")
                        .HasColumnName("struct_type");

                    b.HasKey("Id")
                        .HasName("pk_tracker_tags");

                    b.ToTable("tracker_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = 1,
                            Description = "Версия терминала",
                            Name = "term_version"
                        },
                        new
                        {
                            Id = 2,
                            DataType = 1,
                            Description = "Версия прошивки",
                            Name = "soft"
                        },
                        new
                        {
                            Id = 3,
                            DataType = 4,
                            Description = "IMEI",
                            Name = "imei"
                        },
                        new
                        {
                            Id = 4,
                            DataType = 1,
                            Description = "Идентификатор устройства",
                            Name = "device_id"
                        },
                        new
                        {
                            Id = 5,
                            DataType = 1,
                            Description = "Номер записи в архиве",
                            Name = "rec_sn"
                        },
                        new
                        {
                            Id = 6,
                            DataType = 5,
                            Description = "Дата и время регистрации на трекере",
                            Name = "tracker_date"
                        },
                        new
                        {
                            Id = 7,
                            DataType = 7,
                            Description = "Координаты в градусах, число спутников, признак корректности определения координат и источник координат.",
                            Name = "coord_struct",
                            StructType = 1
                        },
                        new
                        {
                            Id = 8,
                            DataType = 7,
                            Description = "Скорость в км/ч и направление в градусах",
                            Name = "speed_direction",
                            StructType = 2
                        },
                        new
                        {
                            Id = 9,
                            DataType = 1,
                            Description = "Высота, м",
                            Name = "altitude"
                        },
                        new
                        {
                            Id = 10,
                            DataType = 7,
                            Description = "Одно из значений:\n1. HDOP, если источник координат ГЛОНАСС/GPS модуль\n2. Погрешность в метрах, если источник базовые станции GSM-сети",
                            Name = "hdop"
                        },
                        new
                        {
                            Id = 11,
                            DataType = 1,
                            Description = "Статус устройства",
                            Name = "dev_status"
                        },
                        new
                        {
                            Id = 12,
                            DataType = 1,
                            Description = "Напряжение питания, мВ",
                            Name = "pwr_ext"
                        },
                        new
                        {
                            Id = 13,
                            DataType = 1,
                            Description = "Напряжение на батарее",
                            Name = "pwr_int"
                        },
                        new
                        {
                            Id = 14,
                            DataType = 1,
                            Description = "Температура внутри терминала, °С",
                            Name = "temp_int"
                        },
                        new
                        {
                            Id = 15,
                            DataType = 6,
                            Description = "Статус выходов",
                            Name = "out"
                        },
                        new
                        {
                            Id = 16,
                            DataType = 6,
                            Description = "Статус входов",
                            Name = "in"
                        },
                        new
                        {
                            Id = 17,
                            DataType = 1,
                            Description = "Значение на входе 0.\nВ зависимости от настроек один из вариантов:\n1. Напряжение, Мв\n2. число импульсов\n3. частота, Гц",
                            Name = "adc1"
                        },
                        new
                        {
                            Id = 18,
                            DataType = 1,
                            Description = "Значение на входе 1.\nВ зависимости от настроек один из вариантов:\n1. Напряжение, Мв\n2. число импульсов\n3. частота, Гц",
                            Name = "adc2"
                        },
                        new
                        {
                            Id = 19,
                            DataType = 1,
                            Description = "Значение на входе 2.\nВ зависимости от настроек один из вариантов:\n1. Напряжение, Мв\n2. число импульсов\n3. частота, Гц",
                            Name = "adc3"
                        },
                        new
                        {
                            Id = 20,
                            DataType = 1,
                            Description = "Значение на входе 3.\nВ зависимости от настроек один из вариантов:\n1. Напряжение, Мв\n2. число импульсов\n3. частота, Гц",
                            Name = "adc4"
                        },
                        new
                        {
                            Id = 21,
                            DataType = 6,
                            Description = "RS232 0",
                            Name = "adc9"
                        },
                        new
                        {
                            Id = 22,
                            DataType = 6,
                            Description = "RS232 1",
                            Name = "adc10"
                        },
                        new
                        {
                            Id = 23,
                            DataType = 1,
                            Description = "RS485[0]. ДУТ с адресом 0",
                            Name = "RS485[0]"
                        },
                        new
                        {
                            Id = 24,
                            DataType = 1,
                            Description = "RS485[1]. ДУТ с адресом 1",
                            Name = "RS485[1]"
                        },
                        new
                        {
                            Id = 25,
                            DataType = 1,
                            Description = "Данные CAN-шины (CAN_A0) или CAN-LOG.\nТопливо, израсходованное машиной с момента её создания, л",
                            Name = "CAN_A0"
                        },
                        new
                        {
                            Id = 26,
                            DataType = 7,
                            Description = "Данные CAN-шины (CAN_A1) или CAN-LOG.\nУровень топлива, %;\nтемпература охлаждающей жидкости, °C;\nобороты двигателя, об/мин.",
                            Name = "CAN_A1",
                            StructType = 4
                        },
                        new
                        {
                            Id = 27,
                            DataType = 1,
                            Description = "Данные CAN-шины (CAN_B0) или CAN-LOG.\nПробег автомобиля, м.",
                            Name = "CAN_B0"
                        },
                        new
                        {
                            Id = 28,
                            DataType = 7,
                            Description = "CAN8BITR0\nили скорость транспортного средства, передаваемая с CAN-LOG’а, км/ч",
                            Name = "CAN8BITR0"
                        },
                        new
                        {
                            Id = 29,
                            DataType = 7,
                            Description = "CAN8BITR1\nили второй байт префикса S от CAN-LOG",
                            Name = "CAN8BITR1"
                        },
                        new
                        {
                            Id = 30,
                            DataType = 7,
                            Description = "CAN8BITR2\nили первый байт префикса S от CAN-LOG",
                            Name = "CAN8BITR2"
                        },
                        new
                        {
                            Id = 31,
                            DataType = 7,
                            Description = "CAN8BITR3\nили младший байт префикса S от CAN-LOG",
                            Name = "CAN8BITR3"
                        },
                        new
                        {
                            Id = 32,
                            DataType = 7,
                            Description = "CAN8BITR4\nили третий байт префикса P от CAN-LOG",
                            Name = "CAN8BITR4"
                        },
                        new
                        {
                            Id = 33,
                            DataType = 7,
                            Description = "CAN8BITR5\nили второй байт префикса P от CAN-LOG",
                            Name = "CAN8BITR5"
                        },
                        new
                        {
                            Id = 34,
                            DataType = 1,
                            Description = "В зависимости от настроек один из вариантов:\nCAN32BITR0\nполное время работы двигателя, ч",
                            Name = "CAN32BITR0"
                        });
                });

            modelBuilder.Entity("BioTonFMS.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("FuelTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("fuel_type_id");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inventory_number");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("make");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("integer")
                        .HasColumnName("manufacturing_year");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("registration_number");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("TrackerId")
                        .HasColumnType("integer")
                        .HasColumnName("tracker_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int?>("VehicleGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_group_id");

                    b.Property<int>("VehicleSubType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_sub_type");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("FuelTypeId")
                        .HasDatabaseName("ix_vehicles_fuel_type_id");

                    b.HasIndex("TrackerId")
                        .HasDatabaseName("ix_vehicles_tracker_id");

                    b.HasIndex("VehicleGroupId")
                        .HasDatabaseName("ix_vehicles_vehicle_group_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.VehicleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_group");

                    b.ToTable("vehicle_group", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BioTonFMS.Domain.Device", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Tracker", "Tracker")
                        .WithMany("Devices")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_trackers_tracker_id");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("BioTonFMS.Domain.ProtocolTag", b =>
                {
                    b.HasOne("BioTonFMS.Domain.TrackerTag", "Tag")
                        .WithMany("ProtocolTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_protocol_tag_tracker_tags_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BioTonFMS.Domain.Vehicle", b =>
                {
                    b.HasOne("BioTonFMS.Domain.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_fuel_type_fuel_type_id");

                    b.HasOne("BioTonFMS.Domain.Tracker", "Tracker")
                        .WithMany()
                        .HasForeignKey("TrackerId")
                        .HasConstraintName("fk_vehicles_trackers_tracker_id");

                    b.HasOne("BioTonFMS.Domain.VehicleGroup", "VehicleGroup")
                        .WithMany()
                        .HasForeignKey("VehicleGroupId")
                        .HasConstraintName("fk_vehicles_vehicle_group_vehicle_group_id");

                    b.Navigation("FuelType");

                    b.Navigation("Tracker");

                    b.Navigation("VehicleGroup");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("BioTonFMS.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BioTonFMS.Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("BioTonFMS.Domain.Tracker", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("BioTonFMS.Domain.TrackerTag", b =>
                {
                    b.Navigation("ProtocolTags");
                });
#pragma warning restore 612, 618
        }
    }
}
