#!/bin/bash
#Скрипт имеет следующие ключи при запуске
# -h Имя хоста на котором находится база данных
# -p Порт для подключения к базе данных
# -u Пользователь
# -d Директория в которой будут храниться резервные копии
# -r Время хранения резервных копий (Необходимо указать количество в днях)
# --db Название базы данных, копию которой необходимо получить, возможно указать несколько баз.
#
# Пример использоваения ключей для запуска
# bash backup.sh -p 5433 -u bioton -h db.lan.bioton-fms-ru  --db Bioton_test3 --db Bioton_msg_test -d /home/serg/script -r 7 

param_db=()
while [ -n "$1" ]
do
case "$1" in
        -d) directory="$2"
                shift ;;
        --db) param_db+=("$2")
                shift ;;
        -r) retention="$2"
                shift ;;
        -u) user="$2"
                shift ;;
        -h) host="$2"
                shift ;;
        -p) port="$2"
                shift ;;
esac
shift
done

for db in ${param_db[@]}; do
        find $directory \( -name "*.sql.gz" \) -ctime +$retention -delete
        pg_dump -U$user -h$host -p$port -d$db -w | gzip > $directory/$db-$(date "+%Y-%m-%d").sql.gz
done
